### ISSUE TITLE
Observaciones del profesor

### ISSUE THREAD

**Issue by yosbel-penate** [ReSam17/Tareas_DPOO#1]
Crear un árbol de excepciones que tenga que ver con el módulo del negocio que te toca.

**Comment by ReSam17** [comment]
Lo hice pensando en eso, ya que, mi módulo es el controldaor q recibe objetos creados de los démas, por lo tanto me aseguro que en cada campo(atributo) no ocurra ningun error q me impida trabajar con dichos objetos.

**Comment by yosbel-penate** [comment]
Crea cada clase en un archivo de clase diferente, varios desarrolladores quiesieran modificar tus clases, ellos deberian modificar el mismo archivo con el conflicto en git que esto genera. Aunque no está mal lo que has hecho, quiero que tenga que ver más con tu parte del negocio

**Comment by yosbel-penate** [comment]
Cuando hagas esta tarea me pones en el comentario que te la revise,

**Comment by ReSam17** [comment]
Ya separe las excepciones en clases diferentes y tambien subi el CRUD, el ejecutable esta en la carpeta dists

**Comment by ReSam17** [comment]
Ah, y sigo sin aparecer en la tabala con los objetivos a cumplir y tampoco me aparece en issues, de todas formas me parece q ya los cumplí con la tarea de excepciones y el crud, ví por el grupo q dijo q eran 3 tareas puede dejarme aquí cual es la otra?

**Comment by yosbel-penate** [comment]
https://github.com/users/yosbel-penate/projects/9/views/2


![Screenshot_20221120-142132_Chrome.jpg](https://user-images.githubusercontent.com/58090876/202921678-8a9d8282-075b-4724-a619-b3341124d81f.jpg)

**Comment by yosbel-penate** [comment]
Hiciste todas esas tareas? Son tres

**Comment by ReSam17** [comment]
Ya tengo la jerarquía de errores, así como el módulo a desarrolar y el app q subí, pero ahora no estoy seguro q esa app sea de gestión de invitados; ¿Qué debe tener ese tipo de app?

**Comment by yosbel-penate** [comment]
Es solo un crud que permita guardar los datos de los invitados en una lista en el disco duro.

**Comment by ReSam17** [comment]
ah enotnces sí, mire la otra carpeta q está en el repositorio de tareas

**Comment by ReSam17** [comment]
ah enotnces sí, mire la otra carpeta q está en el repositorio de tareas

**Comment by yosbel-penate** [comment]
Inmediatamemte me fijo

**Comment by ReSam17** [comment]
Profe me revisó el CRUD?

**Comment by yosbel-penate** [comment]
voy a eso
